---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ecasorke/public_html

    # Remove old assets
    - /bin/rm -rf $DEPLOYPATH/assets

    # Copy the Vite build
    - /bin/cp -R dist/* $DEPLOYPATH/

    # Copy the PHP API
    - /bin/cp -R public/api $DEPLOYPATH/
